### ISSUE TITLE
Cannot execute sample code and failing sample tests due to missing iam_policy.proto 

### ISSUE THREAD

**Issue by kepikoi** [googleapis/nodejs-kms#100]
#### Environment details

  - OS: Windows 10 Pro 1803
  - Node.js version: 11.5.0
  - npm version: 6.5.0
  - `@google-cloud/kms` version: 0.2.0

#### Steps to reproduce

  1. Add env variables for GOOGLE_APPLICATION_CREDENTIALS and GCLOUD_PROJECT
  2. `mocha samples\system-test\kms.test.js`

every test results following error:
```
Error: google/iam/v1/iam_policy.proto could not be found in C:\www\nodejs-kms\samples\node_modules\@google-cloud\kms\protos
    at Function.GrpcClient._resolveFile (C:\www\nodejs-kms\samples\node_modules\google-gax\build\src\grpc.js:220:15)
    at GrpcClient.loadProto (C:\www\nodejs-kms\samples\node_modules\google-gax\build\src\grpc.js:209:39)
    at new KeyManagementServiceClient (C:\www\nodejs-kms\samples\node_modules\@google-cloud\kms\src\v1\key_management_service_client.js:107:15)
    at quickstart (C:\www\nodejs-kms\samples\quickstart.js:25:18)
    at Object.<anonymous> (C:\www\nodejs-kms\samples\quickstart.js:45:1)
    at Module._compile (internal/modules/cjs/loader.js:721:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:732:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
    at Function.Module._load (internal/modules/cjs/loader.js:552:3)
Error: Error: google/iam/v1/iam_policy.proto could not be found in C:\www\nodejs-kms\samples\node_modules\@google-cloud\kms\protos
    at Function.GrpcClient._resolveFile (samples\node_modules\google-gax\build\src\grpc.js:220:15)
    at GrpcClient.loadProto (samples\node_modules\google-gax\build\src\grpc.js:209:39)
    at new KeyManagementServiceClient (samples\node_modules\@google-cloud\kms\src\v1\key_management_service_client.js:107:15)
    at quickstart (samples\quickstart.js:25:18)
    at Object.<anonymous> (samples\quickstart.js:45:1)
    at Module._compile (internal/modules/cjs/loader.js:721:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:732:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
    at Function.Module._load (internal/modules/cjs/loader.js:552:3)
    at exec (samples\system-test\kms.test.js:42:11)
    at process.internalTickCallback (internal/process/next_tick.js:77:7)

```

When adding the missing file from https://github.com/googleapis/googleapis/blob/master/google/iam/v1/iam_policy.proto all tests execute just fine. I will add a PR with a fix.

Thanks!

**Comment by kinwa91** [comment]
This is Windows-related, the samples test runs fine on CI which runs on linux.
