### ISSUE TITLE
Usage with webpack

### ISSUE THREAD

**Issue by abimelex** [googleapis/nodejs-kms#175]
How to use it correctly with webpack?
Since the *.proto files seems not to be bundled with webpack I struggle a bit here.
The error I get is always:

```
{ Error: ENOENT: no such file or directory, open 'google/cloud/kms/v1/service.proto'
    at Object.openSync (fs.js:436:3)
    at Object.readFileSync (fs.js:341:35)
    at fetch (PATHTOPROJECT/node_modules/protobufjs/src/root.js:160:34)
    at Root.load (PATHTOPROJECT/node_modules/protobufjs/src/root.js:194:13)
    at Root.loadSync (PATHTOPROJECT/node_modules/protobufjs/src/root.js:235:17)
    at Object.loadSync (PATHTOPROJECT/node_modules/@grpc/proto-loader/build/src/index.js:230:27)
    at GrpcClient.loadFromProto (PATHTOPROJECT/node_modules/google-gax/build/src/grpc.js:118:44)
    at GrpcClient.loadProto (PATHTOPROJECT/node_modules/google-gax/build/src/grpc.js:145:21)
    ....
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: 'google/cloud/kms/v1/service.proto' }
```

**Comment by abimelex** [comment]
I found a solution which copies the files to the build directory. Mind that `__dirname` option needs to be set to false. 

webpack options:
```
 node: {
        __dirname: false
    },
    plugins: [
        new CopyPlugin([
            {
                from: './node_modules/@google-cloud/kms/protos',
                to: '../../protos/',
                context: __dirname
            },
        ]),
    ],
```

tested with webpack 3.6
