### ISSUE TITLE
Unable to decrypt the result of an asymmetrically encrypted string using the public key

### ISSUE THREAD

**Issue by holgeradam** [googleapis/nodejs-kms#188]
Hey there,

I was trying to complete an asymmetric encrypt and decrypt cycle using KMS and node. However I am unable to decrypt the ciphertext generated from the public key. Here's an outline of what I did.

- I created a key ring in the region europe-west1.
- I added a key with the following properties:
  - Protection level: Software
  - Purpose: Asymmetric decrypt
  - Default algorithm: 3072 bit RSA key, OAEP Padding - SHA256 Digest
- I changed the decrypt sample from the examples a bit to get started.
- The script retrieves the public key using the cryptoKeyVersionPath.
- The pem encoded string is put into node-forge to create a public key.
- The public key encodes a sample string using the SHA-256 message digest.
- The result is stored as a base64 string.
- This ciphertext is put into the asymmetricDecrypt method to retrieve the original string.

The result is always "Decryption failed."
I suspect that the encryption uses a wrong parameter or setting somewhere, but I can't figure out what it is. The code is added below as well as the output.

Encrypting and decrypting using the CLI example works fine. Encrypting with the CLI and decrypting with node fails, so does the other way around.

Do you see any mistakes here or do you have any idea on how to get the encryption right using node and the retrieved public key? Thank you!

#### Environment details

  - OS: MacOS 10.14.5 with OpenSSL 1.0.2s
  - Node.js version: 10.16.0
  - npm version: 6.9.2
  - `@google-cloud/kms` version: 1.3.0

#### Steps to reproduce

  1. Put the code below into a sample.js file. npm init and install packages.
  2. Run node ./sample.js.

#### Code
```
'use strict';

// [START kms_decrypt]
async function decrypt(
    projectId = 'project-id', // Your GCP projectId
    keyRingId = 'key-ring', // Name of the crypto key's key ring
    cryptoKeyId = 'key', // Name of the crypto key, e.g. "my-key"
    plaintextFileName = './decrypted.txt'
) {
    const fs = require('fs');
    const { promisify } = require('util');
    const { pki, md } = require("node-forge");

    const kms = require('@google-cloud/kms');
    const client = new kms.KeyManagementServiceClient();

    const locationId = 'europe-west1';
    const plaintext = "sample text";
    const unecryptedBuffer = Buffer.from(plaintext);

    const name = client.cryptoKeyVersionPath(
        projectId,
        locationId,
        keyRingId,
        cryptoKeyId,
        "1"
    );

    const [{ pem: publicKey }] = await client.getPublicKey({ name });
    const nfpk = pki.publicKeyFromPem(publicKey);

    var encrypted = nfpk.encrypt(unecryptedBuffer, 'RSA-OAEP', { md: md.sha256.create() });
    const ciphertext = Buffer.from(encrypted).toString("base64");

    const [result] = await client.asymmetricDecrypt({ name, ciphertext });

    const writeFile = promisify(fs.writeFile);
    await writeFile(plaintextFileName + "1", Buffer.from(result.plaintext, 'base64'));
    console.log(
        `Encrypted and decrypted ${plaintext}, result saved to ${plaintextFileName}.`
    );
}
// [END kms_decrypt]

const args = process.argv.slice(2);
decrypt(...args).catch(console.error);

```
#### Result
```
➜ node ./decrypt.js
{ Error: Decryption failed.
    at Http2CallStream.call.on (/[...]/node_modules/@google-cloud/kms/node_modules/@grpc/grpc-js/build/src/client.js:101:45)
    at Http2CallStream.emit (events.js:203:15)
    at process.nextTick (/[...]/node_modules/@google-cloud/kms/node_modules/@grpc/grpc-js/build/src/call-stream.js:71:22)
    at process._tickCallback (internal/process/next_tick.js:61:11)
  code: 3,
  details: 'Decryption failed.',
  metadata:
   Metadata {
     options: undefined,
     internalRepr: Map { 'grpc-server-stats-bin' => [Array] } },
  note:
   'Exception occurred in retry method that was not classified as transient' }
```

**Comment by yacut** [comment]
I have the same problem with the [node-rsa](https://github.com/rzcoder/node-rsa) package. 
```js
        const key = new NodeRSA(publicKey,
            {
                encryptionScheme: {
                    scheme: 'pkcs1_oaep',
                    hash: 'sha256',
                }
            });
        const ciphertext = key.encrypt(Buffer.from(plaintext).toString("base64"), "base64", "base64");

        const [result] = await client.asymmetricDecrypt({ name: asyncKeyName, ciphertext });
        console.log("decrypted: \n" + result.plaintext + "\n");
```
There is also no typescript support for **asymmetricDecrypt** and **getPublicKey** methods.

**Comment by krystianity** [comment]
Here is a simpler version, that can be called after running `npm install @google-cloud/kms`.
Same error, same issue.

```javascript
"use strict";
const kms = require("@google-cloud/kms");

const encrypt = (plaintext, publicKey) => {
    const crypto = require("crypto");
    const buffer = Buffer.from(plaintext, "utf8");
    const encrypted = crypto.publicEncrypt(publicKey, buffer);
    return encrypted.toString("base64");
}

async function encryptDecrypt(
    projectId = "PROJECT_ID",
    keyRingId = "KEY_RING_ID",
    locationId = "europe-west1",
    cryptoKeyId = "CRYPTO_KEY_ID",
    plaintext = "3374395a-0dd4-491a-b0c1-f29e3f330533"
) {
    const client = new kms.KeyManagementServiceClient();
    const asyncKeyName = client.cryptoKeyVersionPath(
        projectId,
        locationId,
        keyRingId,
        cryptoKeyId,
        "1"
    );

    let [{ pem: publicKey, algorithm: algo }] = await client.getPublicKey({ name: asyncKeyName });
    publicKey = publicKey.trim();

    console.log("plaintext: \n" + plaintext + "\n");
    console.log("key: \n" + publicKey + "\n");
    console.log("algo: \n" + algo + "\n");

    const ciphertext = encrypt(plaintext, publicKey);
    console.log("encrypted: \n" + ciphertext + "\n");

    const [result] = await client.asymmetricDecrypt({ name: asyncKeyName, ciphertext });
    console.log("decrypted: \n" + result.plaintext + "\n");
}

const args = process.argv.slice(2);
encryptDecrypt(...args).catch(console.error);
```

**Comment by satorumpen** [comment]
It works well if you specify `mgf1` in node-forge.

```javascript
const forge = require('node-forge')

const pem = `-----BEGIN PUBLIC KEY-----
...
-----END PUBLIC KEY-----`

const publicKey = forge.pki.publicKeyFromPem(pem)
const byte = forge.util.createBuffer('test').getBytes()
const encbin = publicKey.encrypt(byte, 'RSA-OAEP', {
  md: forge.md.sha256.create(),
  mgf1: { md: forge.md.sha256.create() }
})
const encb64 = Buffer.from(encbin, 'binary').toString("base64")

const main = async _ => {
  const client = new kms.KeyManagementServiceClient()
  const name = client.cryptoKeyVersionPath(projectId, locationId, keyRingId, cryptoKeyId, cryptoKeyVersion)
  const [result] = await client.asymmetricDecrypt({name, ciphertext: encb64})
  console.log(Buffer.from(result.plaintext, 'base64').toString("utf8"))
}
main()
```

**Comment by holgeradam** [comment]
Well not quite, but you put me in the right direction.
mgf1 defaults to md in node-forge implementation, if not specified. So it works with and without.
However the error was in creating the Buffer object from the encrypted string. I did not specify an encoding. Using Buffer.from(encrypted, "binary") it works as expected. 

So thank you for getting me unstuck!

**Comment by moander** [comment]
Can someone confirm if @satorumpen 's example using `crypto. publicEncrypt` should work?

 I'm struggling with the same code 3 decryption failed error.
