### ISSUE TITLE
Issue with 1.4.0 release.

### ISSUE THREAD

**Issue by mad-it** [googleapis/nodejs-kms#207]
#### Environment details

  - OS: Ubuntu 18.4
  - Node.js version: 10.x
  - npm version: 6.9.0
  - `@google-cloud/kms` version: 1.4.0

#### Steps to reproduce

Dont really have any steps to reproduce, but I do have a stack trace. This started at 9 PM UTC+2 on our production environment after upgrading from `1.3.2` to `1.4.0`.

Only other thing i can say is that we have pinned `@grpc/grpc-js` to `0.5.2`, because `0.5.3` has a memory leak https://github.com/grpc/grpc-node/issues/1027. 

```
TypeError: Cannot read property 'length' of undefined
    at Root.load (/srv/functions/node_modules/protobufjs/src/root.js:192:44)
    at Root.loadSync (/srv/functions/node_modules/protobufjs/src/root.js:235:17)
    at Object.loadSync (/srv/functions/node_modules/@grpc/proto-loader/build/src/index.js:230:27)
    at GrpcClient.loadFromProto (/srv/functions/node_modules/google-gax/src/grpc.ts:162:40)
    at GrpcClient.loadProto (/srv/functions/node_modules/google-gax/src/grpc.ts:190:17)
    at new KeyManagementServiceClient (/srv/functions/node_modules/@google-cloud/kms/src/v1/key_management_service_client.js:130:28)
    at Object.<anonymous> (/<obfuscated>/index.ts:10:13)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
```

For reproducability. Line 10 of our source code is:
```ts
const kms = new KeyManagementServiceClient();
```

**Comment by callmehiphop** [comment]
👋 @mad-it we've actually been seeing this issue all over the place. It looks like there is an issue with an older version of one of our dependencies being installed. A lot of users have fixed this issue by deleting their `node_modules` and `package-lock.json` files then reinstalling.

**Comment by mad-it** [comment]
:wave: 
Thanks for the update.

For the time being i just pinned to `1.3.2` until this is resolved :)

**Comment by JustinBeckwith** [comment]
Greetings!  Just checking in. If you unpin both this library and `@grpc/grpc-js`, do you still see the issue?

**Comment by mad-it** [comment]
We are currently running on the latest version without `@grpc/grpc-js` pinned without any issues.
The proposed solution by @callmehiphop also worked.
